# Tool Box

# Use Ubuntu 16.04 from Aliyun's registry
FROM w6wy7kfr.mirror.aliyuncs.com/library/ubuntu:16.04

MAINTAINER Da Wei, xichuanglian@gmail.com

ADD sources.list /etc/apt/sources.list
RUN apt-get update