# Percona Server

# Use percona 5.7.15 from Aliyun's registry
FROM w6wy7kfr.mirror.aliyuncs.com/library/percona:5.7.15

MAINTAINER Da Wei, xichuanglian@gmail.com

ADD mysqld.cnf /etc/mysql/percona-server.conf.d/mysqld.cnf