# Nginx

# Use Nginx 1.11.5 from Aliyun's registry
FROM w6wy7kfr.mirror.aliyuncs.com/library/nginx:1.11.5

MAINTAINER Da Wei, xichuanglian@gmail.com

ADD wiki.conf /etc/nginx/conf.d/wiki.conf

EXPOSE 8002